# Generated by Django 2.2.12 on 2020-04-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline', models.TimeField(auto_now=True)),
                ('field', models.TimeField(auto_now_add=True, null=True)),
                ('m2', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
